Feat/introduce ibat lim low high
NordicSemiconductor/pc-nrfconnect-npm pull request #161
Opened 2024-04-26 16:09 UTC by kylebonnici

This PR is to address https://nordicsemi.atlassian.net/browse/PMICSW-103 

Summary 

- We only send 1340 or 271 values that are mapped to High and Low
- Keep GUI able to support future cases where we need to have a slider and not dropdown
- overwrite user manual input to closes values if user has a different value configured.

2024-04-29 07:17 UTC, greg-fer requested changes
Punctuation ticker: 70 NOK.
There are also several typos.

2024-04-29 07:17 UTC, greg-fer commented on src/features/pmicControl/npm/npm1300/charger/chargerCallbacks.ts
> +                                'unable to parse response. UI might be out of sync'
```suggestion
                                'Unable to parse response. UI might be out of sync.'
```

2024-04-29 07:17 UTC, greg-fer commented on src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
> +        'npmx charger iBatLim closes to High should overwrite ans set it to high %p',
```suggestion
        'npmx charger iBatLim closes to High should overwrite and set it to high %p.',
```
Why `High` capitalized? What does `closes to` mean?

2024-04-29 07:17 UTC, greg-fer commented on src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
> +        'npmx charger iBatLim closes to High should overwrite ans set it to low %p',
Same as above.

2024-04-29 07:17 UTC, greg-fer commented on Changelog.md
> +-   Charger BatLim configuration
```suggestion
-   Charger Battery Limit (BatLim) configuration.
```

2024-04-29 08:55 UTC, boundlesscalm commented on src/components/Cards/Power/PowerCard.tsx
> +                            range={npmDevice.getChargerIBatLimRange()}
<!-- Polish comments are like a suggestion, where there is nothing necessarily wrong with the relevant content, there's just some ways to immediately improve the quality.  -->
**polish:** ‏
```suggestion
                            range={chargerIBatLimRange}
```

2024-04-29 08:55 UTC, boundlesscalm commented on src/features/pmicControl/npm/npm1300/charger/chargerCallbacks.ts
> +                    }
Quick question which I believe is more of a general question for this format:
Why is the partial update being above here, despite the actual sending of the command being done only conditionally?
Especially because the setChargerBatLim also emits the same partial event.

2024-04-29 14:00 UTC, kylebonnici commented on src/features/pmicControl/npm/npm1300/tests/commandCallbacks.test.ts
> +        'npmx charger iBatLim closes to High should overwrite ans set it to high %p',
This test has been removed as feature request changed and this is no longe needed .... but what it meant was that give we only allowed 1340 and 271 if user set is to 500 we set it to 270 as it is closer to 271 than 1340

2024-04-29 14:02 UTC, kylebonnici commented on src/features/pmicControl/npm/npm1300/charger/chargerCallbacks.ts
> +                    }
The intention was to overwrite the user input. Given we only allowed 1340 and 271 if user set is to 500 we set it to 270 as it is closer to 271 than 1340.

This has been removed as after discussing with @aasinclair  we concluded it was to aggressive

2024-04-29 15:10 UTC, aasinclair commented
Please update the overlay export to include this new setting.

e.g.:

 dischg-limit-microamp = <${toMicro(charger.iBatLim / 1000)}>;

2024-04-30 06:23 UTC, greg-fer requested changes

2024-04-30 06:23 UTC, greg-fer commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +                        current than 150mA.
This text is advising already. No need to state this.
```suggestion
                        For best fuel gauge accuracy, use
                        <span>IBAT</span>
                        <span className="subscript">LIM_LOW</span> for
                        applications with a lower maximum battery discharge
                        current than 150mA.
```

2024-04-30 07:19 UTC, kylebonnici commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +                        current than 150mA.
@eisl-nordic I am also unsure about the title as @aasinclair  suggested 

Discharge current limit

But all other items are using the label as a the title let me know what is best

2024-04-30 07:26 UTC, eisl-nordic commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +                        current than 150mA.
I assume this will be in the "Charger" card, I think it would be good to add "Battery", so it becomes "Battery Discharge Current Limit", to make it even more clear.

2024-04-30 07:38 UTC, kylebonnici commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +        ],
<img width="318" alt="image" src="https://github.com/NordicSemiconductor/pc-nrfconnect-npm/assets/10996496/c18a93aa-3ca6-44b5-8541-b1bd004a31e2">

2024-04-30 08:58 UTC, kylebonnici commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +        ],
@eisl-nordic ok ? my intention is to merge and we do new PR for the 150 mA as we need to fork out soon

2024-04-30 09:03 UTC, eisl-nordic commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +        ],
Looks good to me, but @aasinclair needs to confirm the 150 mA limit

2024-04-30 10:30 UTC, greg-fer requested changes

2024-04-30 10:30 UTC, greg-fer commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +                        <span>IBAT</span>
```suggestion
                        For best fuel gauge accuracy, use
                        {` `}<span>IBAT</span>{` `}
```
We need blank spaces around this span. Check the image in your comment below.

2024-04-30 11:28 UTC, merged

2024-05-09 15:37 UTC, aasinclair commented on src/features/pmicControl/npm/npm1300/documentationPmic1300.tsx
> +        ],
From simulations limit should be **200 mA**